change lg to xl
Felfio/AAUFood pull request #15
Opened 2016-10-06 10:12 UTC by behackl

2016-10-06 17:12 UTC, phylib commented
I would propose to change `col-xl-3` to `col-xl-3 col-lg-6 col-md-12`. This will introduce a intermediate view for tablets with 2 colums.

2016-10-09 17:52 UTC, Kruemelkatze requested changes
Follow and evaluate suggestions by @phylib

2016-10-09 20:53 UTC, behackl commented
Done, changes LGTM.

2016-10-10 19:30 UTC, phylib approved these changes

2016-10-10 19:31 UTC, phylib approved these changes

2016-10-10 19:33 UTC, merged