Feature/pdfparse
Felfio/AAUFood pull request #49
Opened 2017-10-27 10:30 UTC by phylib

Added PrincS to Cityfood

2017-11-28 21:54 UTC, behackl requested changes
Bis auf diese eine Sache ist mir nichts aufgefallen.

Der Princs-Parser würde wohl etwas mehr Liebe verdienen, ich glaube da wurde in den PDFs layoutmäßig etwas geändert, seit ich den mal irgendwie hingehackt habe.

Ansonsten aber sehr OK, von mir aus kann man das (nach der kleinen Änderung mit der Variablen) mergen. :-)

2017-11-28 21:54 UTC, behackl commented on public/styles/app.scss
> +$princessBg: #e30613;
die variable hier (und unten nochmal) sollte $princsBg heißen :smile:

2017-11-28 21:54 UTC, behackl commented on public/styles/app.scss
> +  @include restaurantColors($princessBg, white);
siehe oben

2017-11-29 07:59 UTC, phylib commented on public/styles/app.scss
> +$princessBg: #e30613;
erledigt :+1:

2017-11-29 08:01 UTC, phylib reviewed
Sieht um einiges aufgeräumter aus als der alte Code. Ich würds approven, Github lässt mich aber nicht weil ich Pull-Request Author bin.

2017-11-30 14:26 UTC, behackl approved these changes

2017-11-30 14:26 UTC, merged